# 项目版本与依赖版本配置
org.gradle.jvmargs=-Xmx2G -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2,TLSv1.3 -Dfile.encoding=UTF-8 -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
loader_version=0.17.2

# Mod Properties
maven_group=com.shiroha233.mmdskin

# Dependencies
fabric_version=0.119.9+1.21.5
neoforge_version=21.5.97
architectury_version=16.1.4
cloth_config_version=18.0.145

# mc-vr-api (Vivecraft VR API)

# 运行游戏时的人物名称
minecraft_username=Developer
